ProjetBundle\Entity\Message:
    type: entity
    table: message
    id:
        idMessage:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_message
            generator:
                strategy: IDENTITY
    fields:
        idExpediteur:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_expediteur
        idDestinataire:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_destinataire
        contenu:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        dateEnvoi:
            type: date
            nullable: false
            column: date_envoi
        pieceJointe:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: piece_jointe
        vue:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
    lifecycleCallbacks: {  }
