ProjetBundle\Entity\Universite:
    type: entity
    table: universite
    id:
        idUniversite:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_universite
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        specialite:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        dirigeant:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        adresse:
            type: integer
            nullable: false
            options:
                unsigned: false
        numTel:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: num_tel
        numPortable:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: num_portable
        fax:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        siteWeb:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
            column: site_web
        igit:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
